### ISSUE TITLE
Continuous logging and injecting parameters

### ISSUE THREAD

**Issue by roaldarbol** [BrianPugh/belay#36]
Hi Brian. Thanks for the amazing project! I'm trying to put it to good use for some scientific experiments (neuroscience in case you'd find it interesting 😊). First of all sorry - this is a dual issue, but I think they make sense together. Do feel free to split them into separate issues if you wish. 

I'd like to be able to do two specific things: 
- Continuously (or semi-continuously) log the output from the board without interrupting it. With `device.task()` I can only log the function output at the end of the function. And with `list_of_values = device.thread()` I haven't been able to return values (I get `NoneType`). I could run a loop locally, but it doesn't offer the same time precision I'm after (I can provide an example if needed). I've written about it previously on the [MicroPython Github](https://github.com/micropython/micropython/discussions/9495) which is where I was recommended to have a look at Belay.
- I need to be able to send updated variables as it is running. I've been able to do that previously with `poll` on the board and `serial.write()` on the local side. See more [on the MicroPython forum](https://forum.micropython.org/viewtopic.php?f=2&t=12663).

Do you think I can achieve this with Belay, or what would be needed? I'd be happy to beta test features if you'd like me to. I can get away with some sloppier code for now, but I'd love to make the most of the tidiness offered by Belay! 😃

**Comment by BrianPugh** [comment]
Thanks for checking out Belay and the kind words! I agree, it would be nice to parse an unprompted stream of values from the device (I've ran into the issue myself!). An issue is that stuff becomes asynchronous, which has its pros and cons. To keep the library (relatively) simple, I've chosen to avoid async behavior. Here are some possible alternatives that might be acceptable:


1. If you only needed to stream values off the device, it might be ok to make your task a generator:

```
@device.task
def my_task():
    while True:
        val = read_sensor()
        yield val
        
for val in my_task():
    print(val)
```

2. It might be ok to start your main loop as a `thread` (it returns `None` because generally the thread will be a long-running loop). Then, query/update values via a ``device.task``, updating global variables:

```
device("import _thread")
device("lock = _thread")
device("foo, bar = 0, 0")

@device.thread
def my_main_loop():
    global foo
    while True:
        with lock:
            foo = 2 * bar
            
@device.task
def set_bar(x):
    global bar
    with lock:
        bar = x

@device.task
def get_foo():
    with lock:
        return foo

my_main_loop()
set_bar(5)
time.sleep(0.5)
foo = get_foo()
```

Admittedly, these aren't very glamorous solutions. If you can propose a new, alternative interface for achieving your desired goals, I'll try and think if I can come up with a way of implementing it!

**Comment by roaldarbol** [comment]
Hadn't tried generators before - that solves the first issue very well and in a clean way!
Do you think it could be a possibility to get `yield` to work within `device.thread()`? 

I also saw that you're using `PyBoard.py` - what I currently use is the `pyb.serial.write()` [as suggested by Dave Hylands](https://forum.micropython.org/viewtopic.php?f=2&t=12663#p68694), and `poll` to register incoming messages on the board. Maybe there's a way of exposing some of the underlying `PyBoard.py` functionality? Then we could start a thread (that we could repeatedly yield from), and send updated parameters using something like `device.serial.write()`?

**Comment by BrianPugh** [comment]
oh! I forgot I implemented this, another solution is to specify `stream_out` in the belay task decoration. The default behavior is to [write to stdout once a newline is reached.](https://github.com/BrianPugh/belay/blob/e4f03284cd7511550419b9b408cf575c3c6de380/belay/device.py#L587) I need to update the docstring to `Device.__call__`.

```
import io
import ast

collected = []
class MyStream(io.TextIOBase):
    def write(self, line):
        data = ast.literal_eval(line)  # if appropriate
        collected.append(data)
        
my_stream = MyStream()
@device.task(stream_out=my_stream)
def my_task():
    for i in range(100):
        print(i)
my_task() # will block until my_task is complete
# TODO: process collected here; it should be [0, 1, 2, ..., 99]
```

**Comment by BrianPugh** [comment]
so the issue with getting data from a thread, is that its hard to process. If we start a thread, then we need to be constantly monitoring the serial connection. If the host computer is blocking doing that, then its really no better than a `task`. If the host computer is **not** blocking, then we need to spin up a thread on the host for monitoring the serial port, which complicates things. An alternative is to migrate to asyncio, but thats a whole can of worms. See if the response I posted at the same time as you helps 😄

**Comment by roaldarbol** [comment]
I still don't quite think it fits the bill 🙈 The above example still blocks until the task finishes.

What about just getting values at regular intervals so it won't be blocking? Would it be possible to do something like `multiprocessing.Queue()` to send batches of data?

I.e. a minimal conceptual example: I run a LED, and record a temperature. I wan't to be able to "manually"/on-the-fly adjust the light intensity, but still get a continuous stream of temperatures. 

Sorry I'm a bit all over the place, I'm trying to figure all this stuff out as we go along.

**Comment by BrianPugh** [comment]
so maybe the best option is threading on the host, and using a generator on-device. This way, there should be very little on-device dead-time. Hopefully one of these solutions works for you! Keep me updated on your journey!

```
import threading
from queue import Queue

@device.task
def my_task():
    while True:
        val = read_sensor()
        yield val
        
my_queue = Queue()

def thread_loop(queue):
    while True:
        data = queue.get()
        # Do expensive data processing here
        
my_thread = threading.Thread(target=thread_loop, args=(my_queue))
my_thread.start()

for val in my_task():
    # Keep this very short so there's very little dead-time on-device.
    my_queue.put(val)
```

**Comment by BrianPugh** [comment]
another option that might help, is I think I can implement the `send` portion of the generator protocol, so I'll give that a try.

**Comment by BrianPugh** [comment]
I just released v0.12.0 that implements the `send` functionality of generators, so now you have another tool to try and solve this problem 😄

**Comment by roaldarbol** [comment]
Oh wow, that was quick - awesome work! 😃 I haven't used `send` before, would you have a minimal example?

**Comment by roaldarbol** [comment]
I've had a good play with it and I think you're right, it looks like a really good solution! However, the implementation doesn't work as expected currently. MRE:

```python
import belay

device = belay.Device('/dev/cu.usbmodem141101') # change to your own... you know

@device.task
def send_settings(settings):
    while True:
        incoming = yield
        if incoming is not None:
            settings['num'] = incoming['num']
        yield(settings)

@device.task
def send_number(num):
    while True:
        incoming = yield
        if incoming is not None:
            num += incoming
        yield(num)

n_1 = 7
n_2 = 8
s_1 = {'num': 7}
s_2 = {'num': 9}
g_1 = send_number(n_1)
g_2 = send_settings(s_1)
g_1.send(None)
g_2.send(None)
o_1 = g_1.send(n_2)
o_2 = g_2.send(s_2)

print(o_1, o_2)
# 7 {'num': 7}
```
Just commenting out `@device.task` it gives the expected:
```python
15 {'num': 9}
```

**Comment by BrianPugh** [comment]
did you upgrade belay to v0.12.0? It gives the expected `15 {'num': 9}` on my computer.

**Comment by roaldarbol** [comment]
Lol... I had... But I hadn't reloaded it... Sorry about that. 😅 Awesome!

**Comment by roaldarbol** [comment]
I'll close this issue for now - if I think of other curious tweaks that would be cool I'll let you know. Thanks again!
